import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/Header'
import { Inter as FontSans } from "next/font/google"
import { cn } from '@/lib/utils'

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: 'Dine Market',
  description: 'Generated by 124aris',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased",fontSans.variable)}>
        <div className='py-4 px-12'>
          <Header/>
          {children}
        </div>
      </body>
    </html>
  )
}
