const ProductsList = [
    {
        ID: 1,
        ProductName: "Brushed Raglan Sweatshirt",
        ProductType: "Sweater",
        Price: 195.00,
        ProductCategory: "Female",
        ProductDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        ProductCare: ["Hand wash using cold water.", "Do not using bleach.", "Hang it to dry.", "Iron on low temperature."],
        ProductPicture: ["/Item1.png"],
    },
    {
        ID: 2,
        ProductName: "Cameryn Sash Tie Dress",
        ProductType: "Dress",
        Price: 545.00,
        ProductCategory: "Female",
        ProductDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        ProductCare: ["Lorem ipsum dolor sit amet", "Lorem ipsum dolor sit amet"],
        ProductPicture: ["/Item2.1.png", "/Item2.2.png", "/Item2.3.png", "/Item2.4.png"],
    },
    {
        ID: 3,
        ProductName: "Flex Sweatshirt",
        ProductType: "Sweater",
        Price: 175.00,
        ProductCategory: "Female",
        ProductDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        ProductCare: ["Hand wash using cold water.", "Do not using bleach.", "Hang it to dry."],
        ProductPicture: ["/Item3.png"],
    },
    {
        ID: 4,
        ProductName: "Flex Sweatpants",
        ProductType: "Pants",
        Price: 175.00,
        ProductCategory: "Female",
        ProductDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        ProductCare: ["Hand wash using cold water.", "Do not using bleach.", "Hang it to dry.", "Iron on low temperature."],
        ProductPicture: ["/Item4.png"],
    },
    {
        ID: 5,
        ProductName: "Pink Fleece Sweatpants",
        ProductType: "Pants",
        Price: 195.00,
        ProductCategory: "Female",
        ProductDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        ProductCare: ["Hand wash using cold water.", "Do not using bleach.", "Hang it to dry.", "Iron on low temperature."],
        ProductPicture: ["/Item5.png"],
    },
    {
        ID: 6,
        ProductName: "Lite Sweatpants",
        ProductType: "Pants",
        Price: 150.00,
        ProductCategory: "Female",
        ProductDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        ProductCare: ["Hand wash using cold water.", "Do not using bleach.", "Hang it to dry.", "Iron on low temperature."],
        ProductPicture: ["/Item6.png"],
    },
    {
        ID: 7,
        ProductName: "Imperial Alpaca Hoodie",
        ProductType: "Jackets",
        Price: 525.00,
        ProductCategory: "Female",
        ProductDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        ProductCare: ["Hand wash using cold water.", "Do not using bleach.", "Hang it to dry.", "Iron on low temperature."],
        ProductPicture: ["/Item7.png"],
    },
    {
        ID: 8,
        ProductName: "Flex Push Button Bomber",
        ProductType: "Jackets",
        Price: 225.00,
        ProductCategory: "Male",
        ProductDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        ProductCare: ["Hand wash using cold water.", "Do not using bleach.", "Hang it to dry.", "Iron on low temperature."],
        ProductPicture: ["/Item8.png"],
    },
    {
        ID: 9,
        ProductName: "Muscle Tank",
        ProductType: "T Shirts",
        Price: 75.00,
        ProductCategory: "Female",
        ProductDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        ProductCare: ["Hand wash using cold water.", "Do not using bleach.", "Hang it to dry.", "Iron on low temperature."],
        ProductPicture: ["/Item9.png"],
    },
    {
        ID: 10,
        ProductName: "Brushed Bomber",
        ProductType: "Jackets",
        Price: 225.00,
        ProductCategory: "Female",
        ProductDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        ProductCare: ["Hand wash using cold water.", "Do not using bleach.", "Hang it to dry.", "Iron on low temperature."],
        ProductPicture: ["/Item10.png"],
    },
    {
        ID: 11,
        ProductName: "Raglan Sweatshirt",
        ProductType: "Sweater",
        Price: 195.00,
        ProductCategory: "Male",
        ProductDetails: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        ProductCare: ["Hand wash using cold water.", "Do not using bleach.", "Hang it to dry.", "Iron on low temperature."],
        ProductPicture: ["/Item11.png"],
    },
];

export default ProductsList;